module.exports = {
    LOAD_DATA: "LOAD ADMIN DATA",
    ADD_CLASS: "ADD CLASS",
    ADD_COURSE: "ADD COURSE",
    ADD_TEACHER: "ADD TEACHER",
    ADD_STUDENT: "ADD STUDENT",
    ADD_ADMIN: "ADD ADMIN",
    ADD_COURSE_ASSIGNINGS: "COURSE ASSIGNINGS",
    ADD_SCHEDULES: "ADD SCHEDULES",
    REPLACE_SCHEDULES: "REPLACE SCHEDULES"
}