module.exports = {
    LOAD_DATA: "LOAD TEACHER DATA",
    REPLACE_SCHEDULES: "REPLACE SCHEDULES",
    ADD_CLASS: "ADD CLASS",
    ADD_COURSE: "ADD COURSE",
    ADD_STUDENT: "ADD STUDENT",
    REPLACE_ASSIGNMENTS: "REPLACE ASSIGNMENTS",
}